### ISSUE TITLE
Create DOI's for SnPM (current and major versions)

### ISSUE THREAD

**Issue by nicholst** [SnPM-toolbox/SnPM-devel#58]
As suggested by @cmaumet [here](https://github.com/NISOx-BDI/NISOx-BDI.github.io/issues/44), let's create DOI's that point to current and major versions of SnPM, where we can then list contributors, much as NiPype does, as described by Chris G in his [blog]( http://blog.chrisgorgolewski.org/2017/11/sharing-academic-credit-in-open-source.html).

**Comment by nicholst** [comment]
This is great!  Thanks Camille.
You said you had to manually set the author list on Zenodo.  Is there a more elegant way to specify authors on Github (without them actually being github contributors) so the author list is automatically updated from github?

(If the answer is a simple "no" is this issue ready to close?)

**Comment by cmaumet** [comment]
Yes, there is a more elegant way by creating a metadata file that is then read by Zenodo at the root of our repository but I could not retrieve the info on what format this file should have... I've open an issue to keep this in mind. I think we can close this one

**Comment by nicholst** [comment]
OK.
