### ISSUE TITLE
README: Remove link to snpm_update and link to releases for details on bug and fixes

### ISSUE THREAD

**Issue by cmaumet** [SnPM-toolbox/SnPM-devel#73]
Now that we are using GitHub for releases and are not creating zip files for updates anymore, let's update the [Bugs and fixes section of the README](https://github.com/SnPM-toolbox/SnPM-devel#snpm13-bugs--fixes) to:
 - Remove mention of `snpm_updates`
 - Refer to https://github.com/SnPM-toolbox/SnPM-devel/releases for informations on bugs and fixes.

@nicholst: is that fine with you?

**Comment by nicholst** [comment]
Yes!
-- 
_________________________________________________________
Thomas Nichols, PhD
Professor of Neuroimaging Statistics
Nuffield Department of Population Health | University of Oxford
Big Data Institute | Li Ka Shing Centre for Health Information and Discovery
Old Road Campus | Headington | Oxford | OX3 7LF | United Kingdom
T: +44 1865 743590 | E: thomas.nichols@bdi.ox.ac.uk
W: http://nisox.org | http://www.bdi.ox.ac.uk

**Comment by TomMaullin** [comment]
This has been addressed by PR #79
